---
- hosts: all
  tasks:
    - name: Disable root login
      lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
    - name: Disable password authentication
      lineinfile: dest=/etc/ssh/sshd_config insertbefore=^#PermitEmpty regexp='^.PasswordAuthentication.*' line="PasswordAuthentication no" state=absent
    - name: Disable PAM
      lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
    - name: Disable challenge response authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
    - name: Restart SSH service
      service: name=sshd state=restarted
