---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "javier"
        groups: "javier"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfm76B5tz/3lQDPPcPMfhbohLgrphm++URq8Y/eMoRh9KmcnTN2/ZZ2d0GekYYUhjz+e2jcLIw1nKC7MwvOK1JNvomcghG7Gxl2g8P0tqPhywDJYVF+E6K+SdL6z9Os2/xl4Sx4kfHL9ZmBg2vQChmEF60pBddUjSHbBS+2HeDPOEzUuNGFLaXmVyA3DHj8unYtniuEDen4BLxWp/JjQtg3bZboQdXM9QFNtUGJuPcounv5cJ6vaMAXPhwSZr25zbLMCdFyn9Kk873+ywDOXRDsHUPOxVRd+an+EXe3KdmlLR1uc12jC+d3aJKA8eJY9C8NHqpsc0Z+MJsXRVU66ZZ javier@Zevenet"

      - username: "javier"
        groups: "javier"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCaMAiL5ryP5KKSuJlpWJafPRtLro1VIARBW1mMfNRdH5GbSt/vx9efH4kaG1bl8eobaSbv0vydl18muAbNNFEJaQncOKJAxYGueugHh6fX+qROypdaXszmmDH1FOWsMbHmA7+YilTAcAZENopiow7whAR5O/bsz/F8IdLES4Ihl0l8EhWw8p14siUfkVIzX5IQ3pK/gV0oSL7/L8BV7vibNtDYVTK0Mn1dkIBszjY6kgGoNEI0F5lnjtO/IKHjHmZCdZZpan8JqlAztxacAg6x2fRWguVzupwaayIJTpMdpErVUU0ne+7WAxXBadLZabA7Wo5pUbyOruYkCJ6oX5L javier@Zevenet"
        password: ""
      - username: "mariano"
        groups: "mariano"
        password: "$6$G.gULXDtEmrwF$xKUgrsr8HfMstO6iQ8Esy6Q5EQaK0JrAyTpg2mmcn5fqwD.8Z.Md4/WjgGG8Yf6iMZBJns66AuqNOCdYc.4h/1"
      - username: "jesus"
        groups: "jesus"
        password: "$6$3brTazJLic6yqJ9T$QJPpL1jGYCpQp1JCYMY4yPhFPcUULqDC8dEOkVYgZdMciZ7zXWVoRjkWqXxNzPFJw0hCq11jGnXDyimMoRbSF/"
    group:
      - group: "mariano"
      - group: "jesus"
  
######################################################################
#Comando para encriptar contraseña mediante consola.
#####apt install whois
##############mkpasswd --method=SHA-512
##############Introducir contraseña y te la cifra. Pegar el chorizo en password=******
#La directiva groups: añade un grupo secundario al usuario. Append lo mete en el grupo aunque el usuario esté creado ya.
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ group }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      password: "{{ item.password }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
