---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "periquito"
        groups: "periquito"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQZOBXFv6bCKOdKq+3saMzD8plB7lfeRLwQAfTaU/s8rXxiXLX6FR0b/DfeO9za6vl3NUmFeiGeH5Pi3LqGZlYX0T1jlXnwfY1GiLp9n3dgx8iei0I+RXXmlHjxD1MXls1deIpe6HCuA66A10d9cmKfnxpsq/Za/czgl2SvnmyZp2K5cQZ5D5Rwc2UflqVjUQ45iokd3UhoD0h8xnYNT9nZjp0ogn53c4kxWdTJwnrZsbQBqT+JCWYutkTIyJqSLn+rEHVkVa5c7uiuCJ7QgrXiu9opE2xQEAwGdC6F/26dgHssnz9P/pZJAbaNVcpaOo5DizH96dqIqunY0isfdxB periquito@Zevenet"
        password: ""
      - username: "periquito"
        groups: "periquito"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZdyYMAAoz2H30c9OoFvdEC+5K7cFgCSYVJiUsua6otGosYc7mnBKqjaLT8GpTumempKHy2iy1ALWGu6VWVY8suK+8RWH4P3EvS9C2Vy6RU+ARrdh5hhM2wsgcf+xAF8Ixxu6prq7kDuCGVVNLuiPtBI/rrOvrFHmwxHGDs3zUwyVQ5y1jsIwbMXZaZAQ88X2DPFPRkdtWnWoaRdm+GNiL4EuwaHM2AzluxM0KcaNas5p+1OmNRj5tKrYMbRRBcCqefKb/qSprGd5eAQxdawSzWu3sLjys3RUJvddifCneAzOHht6TdycLYl+2y9c7KVg7w4jSrgodj0ZMDBJVKLu9 periquito@Zevenet"
        password: ""
      - username: "periquito"
        groups: "periquito"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRkr6OVqdYSBOEPZG5ZQchmTFbS/c2sT1SvUstO3l3GYE5iEtiWjmA1WDGDHNHm9Tz/0smCTAEk93sl32659XIO48FqmAvD72W0VVae6f9zxbm4RxYqh8xurNWvtYi9SsRyow2V8JgGxi6fDeQGlq5DQ4DPNtYuksXi0A637uhwgj5y/oltj0DXsmlfp3O0nUvC+q4leIKg0otcS3FWzSynedDMO/kVMGpeEMaXesBUQ9F2WgjR3S0XmdwqgbvZd1hW54pCPPEe9uopd10ehVpVFbisZ9BMBfe7xL+fY4iNJ41vxUmSMyBPNKQ62xtiKLIvXeCPrST4ef9hQrCckXP periquito@Zevenet"
        password: ""
      - username: "carmen"
        groups: "carmen"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMUDVzytdwRDBxpsOXmmyDuCPOcNLUOvVe0KPzCfMoWfJHml/aSpyAuXjevZsu6j0nTgQP0198TNioUqIMyxftsCYzIuNhDj3TjunACz+pLUrW1h66fwv5cVTkE3DqD5wUJXHMfHnxxMGFnxnYNDH12Oy8CIHiKuTjDurGyQOfVqYxcxzA63Ye0z7k6UCQg2Mw0RCjx4q9toJ0/xFjlnU55mm9FLI3wWhkwIiyJyQa4kdHV3qy73WSS/aKKnJ02izK5w/zV+m2vRSEx8Fgv2dQs2MfvXHOPOo3C8xOugCL6mRa3UR+wf5VTddwSlfrxCofOx4s4Ob6NMLFsL1/XVq/ carmen@Zevenet"
        password: ""
      - username: "mariano"
        groups: "mariano"
        password: "$6$G.gULXDtEmrwF$xKUgrsr8HfMstO6iQ8Esy6Q5EQaK0JrAyTpg2mmcn5fqwD.8Z.Md4/WjgGG8Yf6iMZBJns66AuqNOCdYc.4h/1"
      - username: "jesus"
        groups: "jesus"
        password: "$6$3brTazJLic6yqJ9T$QJPpL1jGYCpQp1JCYMY4yPhFPcUULqDC8dEOkVYgZdMciZ7zXWVoRjkWqXxNzPFJw0hCq11jGnXDyimMoRbSF/"
    group:
      - group: "mariano"
      - group: "jesus"
  
######################################################################
#Comando para encriptar contraseña mediante consola.
#####apt install whois
##############mkpasswd --method=SHA-512
##############Introducir contraseña y te la cifra. Pegar el chorizo en password=******
#La directiva groups: añade un grupo secundario al usuario. Append lo mete en el grupo aunque el usuario esté creado ya.
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ group }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      password: "{{ item.password }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
