---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "keisuke"
        groups: "keisuke"
       publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC26lxi8cO8Y8ojnQGVJ/vkQwC+54hld/+CWGKMipDsnOYcDB38uKBAyTU5gP+qKThNojZSzEEhCtCUw09rGa8LlQE8u5p7htwuKYUNnDyxHrRzkPcFxNqEzB3+04ZUacrWpR5fcXcDUIib2c8YgDjR6gZus+2hbUJbj3SXbV7GWNdXa93jVFKFsWOohuvEu28KHgRBxGAIjMyQfq1XTWbmvsBIQDLtM91JgzI8ebjBFmsKa8EM1LfhsJYjG50uVzeAYLNiv+cOPjqtkNGcve2/xtr4a32cQvkPW2suds12Sm26rYMtynLJoyXft44MA8yM+nksqJe9ym8KhT6cPGL3 keisuke@Zevenet"
      - username: "carmen"
        groups: "carmen"
         publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqhIZZvEwanCY3zW9JV+5XCC0pKwEmXrtcbVYRNXtHZPDi9NFjWLar0mcFomRNAfU3YLknozWw3oXoSk8zhrbL1U5anYkMHze2i/MpsVc23kXqEZUFH0GQPOF5LlsMAZydUwjhdR8L5jI5Nec3aDHtzXY8U0H/nAEykSc7/Ul/cGk4fFz1iCURO6JLx3rC2BUR/atlMwkQ1Jl6F7LQ38+7DqlJJmenYVWvySj/DVFkj2DRiKuNkDj5BoBA4Ac5XBK31Iygm+WXCv16W+M/1a1FGciX3NOZugu5VpYQuzN1WvGp+ZhF0uYGc7JA+u8aB0IQZHFutDNBBHLTM1I8zIs1 carmen@Zevenet"
      - username: "javier"
        groups: "javier"
         publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5ClBYo3RD+766tPfg1JvhY4s6/V5/P3/FwKYCzwck28cuWaw2IPqtkWVYdXPqqC2I8Bvk35xguHkpaAteVUM6snryImJHkQR5KOzY2l3C9Vn7xaFyiXczcb0QHv+MgN+SVydY0R13iPOwFWRAdUKnPrKroI4U0ceIBN15FSZU8gsK+VMA1g32LGkPyiIAguyMI6i9qVhTJsv+vGai1wrq0Ofr/NWXtmXSCqgBZq8FkXfpIRQfXhhN1nTJHDZLoFKOST5vz/Bx7wgvI10hbBVZUHXClj/qvqj9q6bgsssbM2+gKWBeacXduT5by6fgubntHN7PYHG1NvRqHlMMvagP javier@Zevenet"
    grupo:
      - group: "keisuke"
      - group: "carmen"
      - group: "javier"

  
#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
