---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "carmen"
        groups: "carmen"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYON++5GtWOnk5h6FgoVe7Up/HqQn2N9ZQ+X9pbskjpjimIsgUUOhcoVMSn2kTFmffH5kANJVrCJoxyVIG335A7f44dgjGw7UuyGgqGEeMjxebq/AOgaWgNdenoIuoVS513vV2ntYp7gopoUAhtCY4I0rGxwEulkhYS4h4WYbkdg6AeyLxLmatMW+DNge1IKDKPH0tTD3sWqUwJNhv0k2/1eBhLHQK/+bITODrWIFLkAp5eCN4VqNHjOl4Q0EqIELiJt7Ntpch7g/TZh5IUe79dodyBgSlSUmlbtEPGRWniTGJj179a/15eynDUBfcodgJG6pDKVE7LzhHvsJmLOkZ carmen@Zevenet"
      - username: "carmen"
        groups: "carmen"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCimxeLW51JQQiHujYkKDoNW6MbuyPbKSIgMUYx9KKPr0ot6sYSSMX5rthJtbIsOxuA7nYLXTk1l2qatLUREw7EXPxCo4PmbXdd6jhe4x7e2VPVFFnpZHzcKhLgH0Y9klQIO43yCeO0wD7mRIWs8CaVyH3mgbe8xYA/3TrjcyaKitczlyGHbc+i2A4dYp+QD8oxFESCNUVFt33Jk5GJKwOht9X2jL+iR7F9jpYhomZ0E4eFWxiL++91JjQbw7StCmcMhUlUSaAJrGer+YS+4/iUjUpME3MmMNxInqSyxe9TsL70PNHG1SZJQmO1UpNutIPh0EYaBI/5XA6x9F3qUIfp carmen@Zevenet"
      - username: "mariano"
        groups: "mariano"
        password: "$6$G.gULXDtEmrwF$xKUgrsr8HfMstO6iQ8Esy6Q5EQaK0JrAyTpg2mmcn5fqwD.8Z.Md4/WjgGG8Yf6iMZBJns66AuqNOCdYc.4h/1"
      - username: "jesus"
        groups: "jesus"
        password: "$6$3brTazJLic6yqJ9T$QJPpL1jGYCpQp1JCYMY4yPhFPcUULqDC8dEOkVYgZdMciZ7zXWVoRjkWqXxNzPFJw0hCq11jGnXDyimMoRbSF/"
    group:
      - group: "mariano"
      - group: "jesus"
  
######################################################################
#Comando para encriptar contraseña mediante consola.
#####apt install whois
##############mkpasswd --method=SHA-512
##############Introducir contraseña y te la cifra. Pegar el chorizo en password=******
#La directiva groups: añade un grupo secundario al usuario. Append lo mete en el grupo aunque el usuario esté creado ya.
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ group }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      password: "{{ item.password }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
