---
- hosts: all
  tasks:
    - name: Ejecutar script en todas las máquinas
      script: /root/principal.sh
      
- hosts: interno
  tasks:
    - name: Ejecutar script en máquinas internas
      script: /root/interno.sh
- hosts: externo
  tasks:
    - name: Ejecutar script en máquinas externas
      script: /root/externo.sh
