---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "pruebaotro"
        groups: "pruebaotro"
          publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQLzLqYl0kRhbR8AIug25Ea7sR+DrSDGsR/kl75IPnxPrQ4Z+lcs78ucrSXHxHTcqX60uLCiRRQ5ge8wet3Sh4qirAWq/arxZWFJOUMnFE5pM2Y3vh+KC8A/HBIanY64TuTifz454OWXCeNysLTZUF/IriUNiYYhU2RRQuYI3H4QHPEZ4DxnBwyjHuGVry+Q5wHJP2zN0VFkLr//tTXRCkPsle25uwfCXtw4pIKgP9rbCWUrsJ+d1eWUv3fWG/tnYRlDpzd2t+cyDKLIKCPal1RL7D2CLxTYXpaU00Gq+lhGA7x8Z44bH7Srz1McF7o/ibMI1Zvdv859hV9jV764QX otro@Zevenet"
      - username: "prueba"
        groups: "prueba"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeQGUQ0lSQuv/DmDbeZGUkY00reR8C21SHXae4xDI2oepZqzTQPuBJuR2hMhgu0sSPRQURMfReBRV0Is5D3MGpxUDLDrOZfP1uMQiqLTcihm1p7A2Jz38ynsfo02XnHjc40ExgHpr22Aguj/aveMfBSWcwnKesrGNjjdtexK8ZbiFnVsDPRTx+VRsVtHxTk7fmJQiiES+WaPFYRaP0sxCy4/1tLmx7LI6ULQEDn4wfF3IIsCFVzfjIv8gHRk/5bhaCU8ww17QEoRrAq3GXHUfPPZKcn6S45r+lJkUkXd5vM08De2fMM376H3uJhhhEnHQ+TF6TaHQj5acKsleR+0zJ prueba@Zevenet"
    grupo:
      - group: "pruebaotro"
      - group: "prueba"
 
#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
  - name: authorized_keys
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ item.publica }}"
    with_items:
      "{{ users }}"
    
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM yes" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
############### Modificar etc profile.d para hacer modo auditoría  
  - name: Mover archivo bashrc al directorio /etc/profile.d/
    copy: src=/root/Script/bashrc.sh dest=/etc/profile.d/ 
######################## Módulo de iptables genéricas, según hostname y según grupo externo e interno
  - name: Ejecutar script en todas las máquinas
    script: /root/principal.sh
    
- hosts: interno
  tasks:
  - name: Ejecutar script en máquinas internas
    script: /root/interno.sh
    
- hosts: externo
  tasks:
  - name: Ejecutar script en máquinas externas
    script: /root/externo.sh
