---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "otro"
        groups: "otro"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZVgeIk0z5VB0zEUnOS3OI4LgIKr5qcIRb7M/SS+25UwSJMOWf6UTM+ryCz4i5dG5BA0u97fMpERMo27r/IZMm+mvmGMv9HXD+rq+cJFQPYxLZC+3H2xiWJgpJFllwWjHIWLV+SpbiHPdQiu8Znf+wyc6mh4VWN5Cseu1aTQ8tgRAD/23At9GL0UIFs/sCibW1jK2p8Vb3i1rhQkvatjX/52s/GUW4HB6mR5MJgLhTk/hHchASAz8wBq6F/unQAJSF/rVfa/DDqOHLHuwT51bpwh1kMgUfPELWzehqLs3Xj+GB55miJyJqE9CocZjxRzEuEC9IyOPSQvWC1+/N5XWT otro@Zevenet"
      - username: "pruebaotro"
        groups: "pruebaotro"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjyMlCtlmyIilM/EsvdKIsA212DJcsN6gfA92lRq6B+f9EWFXCr2TyYvGv8sN9BhvqgK0y29Skl7YodPCFsv6Jqu2heGnMC9EwVYG0mQnYQNo96wxSMaWNsBaA5xdhx2RhbQ4lf5xa7j4T3kMSS4OR01NsQhl4S2bNCAxgEK03hQcNhRTIzX077mztaJ+TL7DvaZ4H4rucSn/RJGL0KBna4d8PcpvauPML+lxT/f6fJsWNTZEs0SE30iVG9Ne7VRxXGKUYZPlDyvZg3zC710iPOoVV4/CZfCtWFFbjyu5hmmHGfD5jVGEeqgQxOc4fHt0kk4Q/BD/6ynEOG6+Z3WYt pruebaotro@Zevenet"
    grupo:
      - group: "otro"
      - group: "pruebaotro"

#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
  - name: authorized_keys
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ item.publica }}"
    with_items:
      "{{ users }}"
    
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM yes" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
############### Modificar etc profile.d para hacer modo auditoría  
  - name: Mover archivo bashrc al directorio /etc/profile.d/
    copy: src=/root/Script/bashrc.sh dest=/etc/profile.d/ 
######################## Módulo de iptables genéricas, según hostname y según grupo externo e interno
  - name: Ejecutar script en todas las máquinas
    script: /root/principal.sh
    
- hosts: interno
  tasks:
  - name: Ejecutar script en máquinas internas
    script: /root/interno.sh
    
- hosts: externo
  tasks:
  - name: Ejecutar script en máquinas externas
    script: /root/externo.sh
