---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "emilio"
        groups: "emilio"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC24yigLInPcOUICcGFtXnphQhugPHpqaAtuMJQ2uoYkw/C2qd8Li/DRHipIKQasmgZ70/Vw9kMC3xaud4VVmhE53HsYQiLNbAYlC9d2Kpm8EQcLDVkzRETrhdTTzQ8vSpGw8OrIV3p1CPr9GPzMgExjoF2jMLS0fYxQtg/cZM/v5nN1PEwvyizKJdm+TgAs/6hMmlIUNASPGCcEQw5aXTeOH496NVPNJr7T7BqV/rSbyXZkdua9QVukkhEpts0WZBVrRoCIiyNopSpaY/6ZXm19SyYhPSTF5PsWBqoGmKE1osmywUfIk8HA390fWmdEvH0IkFHXJBfMAH3Cdw5SO6l emilio@Zevenet"
      - username: "adan"
        groups: "adan"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1HSzIsz6cjqs3kBJR64l56vTv0E0Koq13hEQyiCkI9zZL6DlMaZzZR7bglyx7RdAowgvrvhx4aa/yfmAgTmUhy1xOZfldZlhMJhZ/v2ko/erM142eSSaDmDpJ+VvzZ4Vi8MGvgRxVlj3YKGVO8hPKPPFIGqnQP56gszC1jeIpIKSDXwpn9cmOT+yV0Ic0AETUGuFH7uZ3FgShSneRg7o19hCyGunqsu5FcUddJx9XphKVDlH0E1mqEbOWrHY+WiKN8bIbrXGQNODWGF93gvLfR+9RI/QUg9RH80/wcPTrVfC5ZcMdkrBeBRKi2avlYeNFY8M5ecgh/wYY0xfuF85h adan@Zevenet"
    grupo:
      - group: "emilio"
      - group: "adan"




  
#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
  - name: create directory .ssh
    file: 
        path: /home/ {{ item.username }} /.ssh 
        state: directory
    with_items:
      "{{ users }}"
  - name: create empty file authorized_keys
    file:
        path: /home/ {{ item.username }} /.ssh/authorized_keys 
        state: touch
    with_items:
      "{{ users }}"
  - name: send public key
    lineinfile: 
        path: /home/ {{ item.username }} /.ssh/authorized_keys 
        line: "{{ item.publica }}"
    with_items:
      "{{ users }}"
    
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
############### Modificar etc profile.d para hacer modo auditoría  
  - name: Mover archivo bashrc al directorio /etc/profile.d/
    copy: src=/root/Script/bashrc.sh dest=/etc/profile.d/ 
######################## Módulo de iptables genéricas, según hostname y según grupo externo e interno
  - name: Ejecutar script en todas las máquinas
    script: /root/principal.sh
    
- hosts: interno
  tasks:
  - name: Ejecutar script en máquinas internas
    script: /root/interno.sh
    
- hosts: externo
  tasks:
  - name: Ejecutar script en máquinas externas
    script: /root/externo.sh
