---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "carmenmaria.rufo"
        groups: "carmenmaria.rufo"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+w1Er+Wh6lRAkO9/a/tqwTDrzu7su4T62rEpfbSpsv5HS/DbW+8wQwGQtp2ezyxLktmaCGTwUS72Cdzsgfyuwpfvnq0V8eJImIPhzd+lwfJjhSkDOeqbmmXcaTY9VDTyHDjWzLXQ5e/T0n48VMWyT/h/ICIktZQZextzG5jQzdGAU4vrQaaT/QetXcHv8upFbmRG6s92mICjeXJ4oUfe8j2Tu3et5+EQlEDbc88ncyCSVdc9WdFj0ej4tT6fwDlrmYtKMeAs415/8I/zM+8kAJbgSERtRi9SQD/+JnKP3UMJS2F65ok770OXN4d7rSHi7Uc5jV/ClOsU7+K4qdoOF carmenmaria.rufo@Zevenet"
      - username: "javier.bernal"
        groups: "javier.bernal"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+wrq0IBCD+rBjwVeIonz+Dh7wDrvQo4SVQMVegLWCxFwozECdwSQ2bLO0cgHE89+PNC0vXL1tfWML4rdYYS+muViS75UmlHh/GNeb6EVAVDGLIGj8BZt6/BxW8z4vcA/DkUCCKF6lSl/j+mPfml7aA0ghl16VoDWjMxwiPnyE7B9I8p9nsWaTGM5+ulIAls1reLzCtaeD8lp++rGwuQtZelucGdSYydrzF+azCKe5/DIZDHnQ5+HJvbGJikc91pTZQAVllyxr3UyTQEiCrlKe3u596RHR5wsVN0KGXqPtawiHFwL36PzxTjTnKCmIBjib1a/cDwIUvni4voj9ESWj javier.bernal@Zevenet"
    grupo:
      - group: "carmenmaria.rufo"
      - group: "javier.bernal"


#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
  - name: authorized_keys
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ item.publica }}"
    with_items:
      "{{ users }}"
    
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password"
  - name: Permit pubkey authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PubkeyAuthentication' line='PubkeyAuthentication yes'
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PasswordAuthentication' line="PasswordAuthentication no"
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM yes"
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#?ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no"
  - name: Restart SSH service
    service: name=sshd state=restarted
############### Modificar etc profile.d para hacer modo auditoría  
  - name: Mover archivo bashrc al directorio /etc/profile.d/
    copy: src=/root/Script/bashrc.sh dest=/etc/profile.d/ 
######################## Módulo de iptables genéricas, según hostname y según grupo externo e interno
- hosts: externo
  tasks:
  - name: Ejecutar script en máquinas externas
    script: /root/rclocalexterno.sh
