---
- hosts: all
############################VARIABLES##################################
  vars:
    users:
      - username: "pruebaotro"
        groups: "pruebaotro"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCm1Lvi19K+sx1iyBJ8vXGmdHpFRTTcynfvSPvq49s4MNJTiP7GwnPyxkwHLJRVcKzg/wdy/sk/VIKc2yDgnEOTY8oT8LFJZyl0GYbd7BHMDSuY2wMqxwTb8QpNP6kMJsii+/f7Bmr2WrI1GkB5OWG1FmFxHua2NnVAY6YpGaS/DOSMTWtHnUPzfca8aNavP5k39C3LmPD/r9gMnYNYGFUsulMmPTBbVLiwz+oZmBfXtNh6/0gXPF3lab2KrYeTxVSMK5nhaxkb7AQaotauwPsBNnFBnq261ygYUaPuyArM+zKHrIBSjHGJbe5IXaAsN2iyYOpiUn1KZluNr2TMecRp pruebaotro@Zevenet"
      - username: "otro"
        groups: "otro"
        publica: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQayN1ZklsbwoAxCp/lyWGhSIv7rIhO8qrR8e1gAzB6uRuWUQTrIpIgVi6GoVadd98N53Po1yN2mmCJ3oLkfF81ugFc8K7WejQRkrHmOmmGQaSfEvSNf4uCdofz+TMx0J3fl3wvEg5G4Yqoi2OyGWLVqUvOQCiOcApRWKM9J/erS4v+fB7V5BM7slyM3kv/qKgTZuuik90s/EeOquv96L5MbW8h5R1AuR1ZTnm7l3zorrB6t7ZL66kGQfPEgvIt75D0eDPag1bNsod98DNI5uoaIocvHFDoWkYiFs2dwnsg4VRXgMWbgMVcxGhDFu7T5jZEJZa5NB8YOBvpE/dCqhz otro@Zevenet"
    grupo:
      - group: "pruebaotro"
      - group: "otro"

#####################################################################
  tasks:
##################INSTALACIÓN DE SUDO
  - name: install sudo
    apt: name=sudo update_cache=yes state=latest
#####################CREAR GRUPOS MEDIANTE VARIABLE.###########
######CREA TODOS LOS GRUPOS QUE ESTÁN EN LA VARIABLE GROUP.###################
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ grupo }}"
####################CREA USUARIOS QUE ESTÁN EN LA VARIABLE  USERS CON LOS ATRIBUTOS DE CADA UNO DE LOS USERNAME
#######################VAMOS AÑADIENDO ITEMS POR CADA USUARIO DIFERENTE
#######################REALIZAMOS UN BUCLE QUE VA COGIENDO CADA ATRIBUTO = VALOR QUE HEMOS AÑADIDO
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      group: "{{ item.groups }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      "{{ users }}"
  - name: authorized_keys
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ item.publica }}"
    with_items:
      "{{ users }}"
    
############################DIRECTIVAS PARA EL FICHERO ETC/SSH/SSHD_CONFIG
  - name: Disable root login
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin prohibit-password" state=present
  - name: Disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#PasswordAuthentication' line="PasswordAuthentication no" state=present
  - name: Enable PAM
    lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM yes" state=present
  - name: Disable challenge response authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^ChallengeResponseAuthentication' line="ChallengeResponseAuthentication no" state=present
  - name: Restart SSH service
    service: name=sshd state=restarted
############### Modificar etc profile.d para hacer modo auditoría  
  - name: Mover archivo bashrc al directorio /etc/profile.d/
    copy: src=/root/Script/bashrc.sh dest=/etc/profile.d/ 
######################## Módulo de iptables genéricas, según hostname y según grupo externo e interno
  - name: Ejecutar script en todas las máquinas
    script: /root/principal.sh
    
- hosts: interno
  tasks:
  - name: Ejecutar script en máquinas internas
    script: /root/interno.sh
    
- hosts: externo
  tasks:
  - name: Ejecutar script en máquinas externas
    script: /root/externo.sh
