---
- hosts: all
  tasks:
    - name: Ejecutar script
      script: /root/rclocalDEF.sh
- hosts: [ Interno ]
  tasks:
    - name: Ejecutar script en máquinas internas iptables
      script:
- hosts: [ Externo ]
  tasks:
    - name: Ejecutar script en máquinas externas iptables
      script: 
